spring:
  application:
    name: SuzanoIT-QA
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/suzanoit_qa}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/suzanoit_qa}
    user: ${SPRING_FLYWAY_USER:postgres}
    password: ${SPRING_FLYWAY_PASSWORD:postgres}

server:
  port: 8080
